### ISSUE TITLE
C17 TC

### ISSUE THREAD

**Issue by Chu127001** [Chu127001/bounty_1#21]
some text

**Comment by Chu127001** [comment]
1234

**Comment by churik** [comment]
sdfsdfdsfsdf

**Comment by churik** [comment]
![files_8d9aa80a-d35d-42_1](https://user-images.githubusercontent.com/4557972/33212347-4f01fc86-d12b-11e7-8efa-f2b97bcdb255.jpg)

**Comment by status-open-bounty** [comment]
Current balance: 0.000001 ETH
Contract address: [0x1eaee9468a748c3c27c593c92f771263dcea2045](https://ropsten.etherscan.io/address/0x1eaee9468a748c3c27c593c92f771263dcea2045)
![QR Code](https://openbounty.status.im:444/qr/Chu127001/bounty_1/bounty/21/2db214e604ff3780a9520e33a1864e6c25431830b650473b0213ea77b26edb7e/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://openbounty.status.im:444](https://openbounty.status.im:444) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
